### ISSUE TITLE
能否加入上课通知的功能

### ISSUE THREAD

**Issue by jeckorf** [MonsterNone/courseNua#1]
可以利用小程序通知的功能，给用户发送上课通知

**Comment by jeckorf** [comment]
另外如果可以我能帮助一起开发完善

**Comment by MonsterNone** [comment]
暂时没有开发上课通知的计划。

以下是我个人的想法：
1. 由于小程序的特性，如果要增加上课通知就必须在云端保存用户数据（至少是课表）。
2. 记得上课这种事情应该主要靠自觉🤔？（我瞎说的，有时候这周忽然开课我也会忘）

**Comment by MonsterNone** [comment]
当然pull request是非常欢迎的😊上课通知模块如果能做成云函数合并到项目里来非常棒🎉

**Comment by MonsterNone** [comment]
> 另外如果可以我能帮助一起开发完善

新的开发计划已经写进了README里面；您有更好的想法也可以提出/实现。
非常感谢您的支持。
